export const TUTORIAL_STEPS = [
  {
    id: 'welcome',
    title: '👋 ¡Bienvenido a Vendix!',
    description: 'Te guiaremos rápidamente en cómo administrar tu inventario, registrar ventas y generar reportes profesionales.\n\n¡Sólo tomará 1 minuto!',
    target: null,
    route: 'dashboard',
  },
  {
    id: 'dashboard',
    title: '📊 Resumen del Negocio',
    description: 'Conoce tus ventas del día, la valuación total de tu inventario y alertas automáticas de productos con poco stock.',
    target: 'dashboard_view',
    route: 'dashboard',
  },
  {
    id: 'products',
    title: '📦 Catálogo de Productos',
    description: 'Gestiona tu inventario completo: edita precios, actualiza el stock, asigna categorías y busca rápidamente cualquier producto.',
    target: 'products_view',
    route: 'products',
  },
  {
    id: 'new_product',
    title: '➕ Registrar Nuevo Producto',
    description: 'Agrega nuevos productos escaneando su código de barras con la cámara o generando un código automático en 1 clic.',
    target: 'new_product_btn',
    route: 'products',
  },
  {
    id: 'new_sale',
    title: '🛒 Punto de Venta (POS)',
    description: 'Realiza cobros rápidos agregando productos al carrito, escaneando códigos o buscando por nombre. Acepta Yape, Efectivo o Tarjeta.',
    target: 'new_sale_view',
    route: 'scanner',
  },
  {
    id: 'sales_history',
    title: '📜 Historial de Ventas',
    description: 'Revisa las transacciones pasadas con hora exacta, método de pago utilizado y lista detallada de productos cobrados.',
    target: 'sales_history_view',
    route: 'sales',
  },
  {
    id: 'reports',
    title: '📈 Reportes Ejecutivos',
    description: 'Analiza tus ingresos en soles y exporta el reporte oficial en PDF ("Reporte_Vendix.pdf") listo para compartir por WhatsApp.',
    target: 'reports_view',
    route: 'reports',
  },
  {
    id: 'navigation',
    title: '📱 Barra de Navegación',
    description: 'Accede al instante a todas las herramientas del sistema desde la barra inferior adaptada a tu dispositivo.',
    target: 'bottom_tab_bar',
    route: 'dashboard',
  },
  {
    id: 'final',
    title: '🎉 ¡Todo Listo!',
    description: 'Ya conoces las funciones principales de Vendix.\n\nComienza ahora a controlar y hacer crecer tu negocio.',
    target: null,
    route: 'dashboard',
  }
];
